/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

/**
 * Ventana con los datos del proyecto y de las estructuras que se utilizaron.
 *
 * @author Grupo 3
 */
public class AcercaDialog extends javax.swing.JDialog {

    /**
     * Creates new form AcercaDialog
     */

    //Constructor
    public AcercaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Acerca de");
        setResizable(false);
        setLocationRelativeTo(parent);

        //La barra queda fija; el disenador no conserva esta propiedad
        jToolBar1.setFloatable(false);
        txtInfo.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de");

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Biblioteca Nova"));
        pnlDatos.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitulo.setText("Sistema de Préstamos de Libros");
        pnlDatos.add(lblTitulo, java.awt.BorderLayout.NORTH);

        txtInfo.setEditable(false);
        txtInfo.setColumns(44);
        txtInfo.setRows(19);
        txtInfo.setText("Curso: SC-304 Estructura de Datos\nGrupo 3\n\nIntegrantes:\n  - Alejandro Chavarría Ramírez\n  - Andrés Brenes Herrera\n  - Saúl Amir Alvarado Montero\n  - Josel Pablo Vargas Calderón\n\nEstructuras de datos utilizadas:\n  - Árbol binario de búsqueda: catálogo de libros, búsqueda O(log n),\n    con recorridos inorden, preorden y postorden\n  - Lista simplemente enlazada: ejemplares de cada libro y préstamos\n  - Lista doblemente enlazada: usuarios de la biblioteca\n  - Cola FIFO: reservas, se atienden por orden de llegada\n  - Pila LIFO: historial de devoluciones, lo más reciente arriba\n\nTodas las estructuras están hechas con nodos propios, sin usar\ncolecciones de Java.\n\nMódulo de sanciones:\n  - Plazo del préstamo: 7 días\n  - Multa: 500 colones por día de atraso\n  - Con 3 atrasos el usuario queda suspendido; se reactiva a mano\n    desde la pestaña de usuarios");
        jScrollPane1.setViewportView(txtInfo);

        pnlDatos.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        btnAceptar.setText("Aceptar");
        btnAceptar.setFocusable(false);
        btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAceptar);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Cierra la ventana
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JTextArea txtInfo;
    // End of variables declaration//GEN-END:variables
}
