/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import BibliotecaNova.Devolucion;
import exceptions.BibliotecaException;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import service.GestorPrestamos;

/**
 * Formulario de la devolución. Calcula los días de atraso y la multa, y apila
 * el movimiento en el historial.
 *
 * @author Grupo 3
 */
public class DevolucionDialog extends javax.swing.JDialog {

    private GestorPrestamos gestorPrestamos;

    // Codigo del libro que se acaba de devolver, para revisar la cola de reservas
    private String libroDevuelto;

    /**
     * Creates new form DevolucionDialog
     */

    //Constructor
    public DevolucionDialog(java.awt.Frame parent, boolean modal, GestorPrestamos gestorPrestamos,
            String codigoPrestamo) {

        super(parent, modal);
        initComponents();
        this.gestorPrestamos = gestorPrestamos;
        setTitle("Registrar Devolución");
        setResizable(false);
        setLocationRelativeTo(parent);

        //La barra queda fija; el disenador no conserva esta propiedad
        jToolBar1.setFloatable(false);

        //Si venia una fila seleccionada, el codigo llega listo
        if (codigoPrestamo != null) {
            txtPrestamo.setText(codigoPrestamo);
        }

        txtFecha.setText(LocalDate.now().toString());
        lblMulta.setText("Multa: " + String.format("%,.0f", GestorPrestamos.MULTA_POR_DIA)
                + " colones por cada día de atraso.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlDatos = new javax.swing.JPanel();
        lblPrestamo = new javax.swing.JLabel();
        txtPrestamo = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblMulta = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Devolución");
        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la devolución"));
        pnlDatos.setLayout(new java.awt.GridBagLayout());

        lblPrestamo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrestamo.setText("Código del préstamo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 14, 6, 8);
        pnlDatos.add(lblPrestamo, gridBagConstraints);

        txtPrestamo.setPreferredSize(new java.awt.Dimension(180, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 6, 14);
        pnlDatos.add(txtPrestamo, gridBagConstraints);

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFecha.setText("Fecha (aaaa-mm-dd):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(6, 14, 6, 8);
        pnlDatos.add(lblFecha, gridBagConstraints);

        txtFecha.setPreferredSize(new java.awt.Dimension(180, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 14);
        pnlDatos.add(txtFecha, gridBagConstraints);

        lblMulta.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        lblMulta.setForeground(new java.awt.Color(102, 102, 102));
        lblMulta.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(10, 14, 12, 14);
        pnlDatos.add(lblMulta, gridBagConstraints);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        btnGuardar.setText("Registrar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Registra la devolucion y apila el movimiento en el historial
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        LocalDate fecha;

        try {
            fecha = LocalDate.parse(txtFecha.getText().trim());
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, "La fecha debe venir en el formato aaaa-mm-dd.",
                    "Devolución", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {

            Devolucion devolucion = gestorPrestamos.registrarDevolucion(txtPrestamo.getText().trim(), fecha);

            String mensaje = "Devolución registrada.\n\n"
                    + "Préstamo: " + devolucion.getCodigoPrestamo() + "\n"
                    + "Ejemplar: " + devolucion.getCodigoEjemplar() + "\n"
                    + "Días de atraso: " + devolucion.getDiasAtraso() + "\n"
                    + "Multa: " + String.format("%,.2f", devolucion.getMulta()) + " colones";

            if (devolucion.getDiasAtraso() > 0) {
                mensaje = mensaje + "\n\nSe le sumó un atraso al usuario " + devolucion.getCarneUsuario() + ".";
            }

            libroDevuelto = devolucion.getCodigoLibro();

            JOptionPane.showMessageDialog(this, mensaje, "Devolución", JOptionPane.INFORMATION_MESSAGE);
            dispose();

        } catch (BibliotecaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Devolución",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    //Cierra el formulario sin guardar
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Libro que se devolvio, o null si no se registro nada. La ventana
     * principal lo usa para revisar si alguien lo tiene reservado.
     */
    public String getLibroDevuelto() {
        return libroDevuelto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMulta;
    private javax.swing.JLabel lblPrestamo;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPrestamo;
    // End of variables declaration//GEN-END:variables
}
