/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import BibliotecaNova.Libro;
import exceptions.BibliotecaException;
import javax.swing.JOptionPane;
import service.GestorLibros;

/**
 * Formulario para agregar un ejemplar físico a la lista enlazada de un libro.
 *
 * @author Grupo 3
 */
public class EjemplarDialog extends javax.swing.JDialog {

    private GestorLibros gestorLibros;
    private String codigoLibro;

    /**
     * Creates new form EjemplarDialog
     */

    //Constructor
    public EjemplarDialog(java.awt.Frame parent, boolean modal, GestorLibros gestorLibros, String codigoLibro) {
        super(parent, modal);
        initComponents();
        this.gestorLibros = gestorLibros;
        this.codigoLibro = codigoLibro;
        setTitle("Agregar Ejemplar");
        setResizable(false);
        setLocationRelativeTo(parent);

        //La barra queda fija; el disenador no conserva esta propiedad
        jToolBar1.setFloatable(false);

        Libro libro = gestorLibros.buscarLibro(codigoLibro);

        txtLibro.setText(codigoLibro);
        txtLibro.setEditable(false);

        if (libro != null) {
            lblLibroTitulo.setText(libro.getTitulo());
            //Propone el siguiente consecutivo del ejemplar
            txtCodigo.setText("E-" + libro.getCodigo().replace("L-", "") + "-"
                    + (libro.getListaEjemplares().contar() + 1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlDatos = new javax.swing.JPanel();
        lblLibro = new javax.swing.JLabel();
        txtLibro = new javax.swing.JTextField();
        lblLibroTitulo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Ejemplar");
        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del ejemplar"));
        pnlDatos.setLayout(new java.awt.GridBagLayout());

        lblLibro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLibro.setText("Libro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 14, 6, 8);
        pnlDatos.add(lblLibro, gridBagConstraints);

        txtLibro.setPreferredSize(new java.awt.Dimension(220, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 6, 14);
        pnlDatos.add(txtLibro, gridBagConstraints);

        lblLibroTitulo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblLibroTitulo.setForeground(new java.awt.Color(102, 102, 102));
        lblLibroTitulo.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 14);
        pnlDatos.add(lblLibroTitulo, gridBagConstraints);

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodigo.setText("Código del ejemplar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(6, 14, 12, 8);
        pnlDatos.add(lblCodigo, gridBagConstraints);

        txtCodigo.setPreferredSize(new java.awt.Dimension(220, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 12, 14);
        pnlDatos.add(txtCodigo, gridBagConstraints);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        btnGuardar.setText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Agrega el ejemplar al final de la lista enlazada del libro
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {

            gestorLibros.agregarEjemplar(codigoLibro, txtCodigo.getText());

            JOptionPane.showMessageDialog(this, "Ejemplar agregado a la lista del libro.");
            dispose();

        } catch (BibliotecaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Agregar ejemplar",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    //Cierra el formulario sin guardar
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblLibroTitulo;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtLibro;
    // End of variables declaration//GEN-END:variables
}
