/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import BibliotecaNova.Prestamo;
import BibliotecaNova.Reserva;
import exceptions.BibliotecaException;
import exceptions.PrestamoNoPermitidoException;
import javax.swing.JOptionPane;
import service.GestorPrestamos;

/**
 * Formulario del préstamo. Cuando el libro no tiene ejemplares libres, ofrece
 * dejar al usuario en la cola de reservas.
 *
 * @author Grupo 3
 */
public class PrestamoDialog extends javax.swing.JDialog {

    private GestorPrestamos gestorPrestamos;

    /**
     * Creates new form PrestamoDialog
     */

    //Constructor
    public PrestamoDialog(java.awt.Frame parent, boolean modal, GestorPrestamos gestorPrestamos) {
        super(parent, modal);
        initComponents();
        this.gestorPrestamos = gestorPrestamos;
        setTitle("Registrar Préstamo");
        setResizable(false);
        setLocationRelativeTo(parent);

        //Se fija aqui porque el disenador no conserva esta propiedad
        jToolBar1.setFloatable(false);

        lblPlazo.setText("El préstamo vence a los " + GestorPrestamos.DIAS_PRESTAMO + " días.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlDatos = new javax.swing.JPanel();
        lblCarne = new javax.swing.JLabel();
        txtCarne = new javax.swing.JTextField();
        lblLibro = new javax.swing.JLabel();
        txtLibro = new javax.swing.JTextField();
        lblPlazo = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Préstamo");
        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del préstamo"));
        pnlDatos.setLayout(new java.awt.GridBagLayout());

        lblCarne.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCarne.setText("Carné del usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 14, 6, 8);
        pnlDatos.add(lblCarne, gridBagConstraints);

        txtCarne.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 6, 14);
        pnlDatos.add(txtCarne, gridBagConstraints);

        lblLibro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLibro.setText("Código del libro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(6, 14, 6, 8);
        pnlDatos.add(lblLibro, gridBagConstraints);

        txtLibro.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 14);
        pnlDatos.add(txtLibro, gridBagConstraints);

        lblPlazo.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        lblPlazo.setForeground(new java.awt.Color(102, 102, 102));
        lblPlazo.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(10, 14, 12, 14);
        pnlDatos.add(lblPlazo, gridBagConstraints);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        btnGuardar.setText("Prestar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Presta, o encola la reserva si no hay ejemplares libres
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {

            Prestamo prestamo = gestorPrestamos.registrarPrestamo(txtCarne.getText(), txtLibro.getText());

            JOptionPane.showMessageDialog(this,
                    "Préstamo registrado.\n\n"
                    + "Código: " + prestamo.getCodigoPrestamo() + "\n"
                    + "Ejemplar entregado: " + prestamo.getCodigoEjemplar() + "\n"
                    + "Debe devolverlo el " + prestamo.getFechaVencimiento(),
                    "Préstamo", JOptionPane.INFORMATION_MESSAGE);

            dispose();

        } catch (PrestamoNoPermitidoException ex) {

            //Sin ejemplares libres, se le ofrece la cola
            int respuesta = JOptionPane.showConfirmDialog(this,
                    ex.getMessage() + "\n\n¿Desea dejar la reserva en la cola?",
                    "Préstamo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (respuesta == JOptionPane.YES_OPTION) {
                registrarReserva();
            }

        } catch (BibliotecaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Préstamo",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    //Deja al usuario en la cola
    private void registrarReserva() {

        try {

            Reserva reserva = gestorPrestamos.registrarReserva(txtCarne.getText(), txtLibro.getText());

            JOptionPane.showMessageDialog(this,
                    "Reserva " + reserva.getCodigoReserva() + " encolada.\n"
                    + "Turno en la cola: " + gestorPrestamos.getReservas().contar(),
                    "Cola de reservas", JOptionPane.INFORMATION_MESSAGE);

            dispose();

        } catch (BibliotecaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Cola de reservas",
                    JOptionPane.WARNING_MESSAGE);
        }
    }

    //Sale sin guardar nada
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblCarne;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblPlazo;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JTextField txtCarne;
    private javax.swing.JTextField txtLibro;
    // End of variables declaration//GEN-END:variables
}
